/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as ApiWereadRouteImport } from './routes/api.weread'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWereadRoute = ApiWereadRouteImport.update({
  id: '/api/weread',
  path: '/api/weread',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/api/weread': typeof ApiWereadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/api/weread': typeof ApiWereadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/api/weread': typeof ApiWereadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/converter' | '/api/weread'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/converter' | '/api/weread'
  id: '__root__' | '/' | '/converter' | '/api/weread'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConverterRoute: typeof ConverterRoute
  ApiWereadRoute: typeof ApiWereadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weread': {
      id: '/api/weread'
      path: '/api/weread'
      fullPath: '/api/weread'
      preLoaderRoute: typeof ApiWereadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConverterRoute: ConverterRoute,
  ApiWereadRoute: ApiWereadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
